/***********************************************
Author: Kyle 
Associated Filename: full_connection_test.cpp
Purpose:to verify the acceleration of the full_connection_layer
Device: All 
Revision History: July 28,2020
------------------------------------------
Meanings of registers:
input_data_buf      ---->   vector of input data(1D)
output_data_sw      ---->   vector of output data(1D) generated by softwares
output_data_hw      ---->   vector of output data(1D) generated by hardwares
weights_buf         ---->   Matrix of weights data(2D)
weights_flatten_buf ---->   vector(1D) flatten by the weights_buf
***********************************************/

#include "full_connection_layer.h"
#include "iostream"

using namespace std;

int main()
{
    float input_data_buf[INPUT_NUM1] = {1, 2, 3};
    float output_data_sw[OUTPUT_NUM1];
    float output_data_hw[OUTPUT_NUM1];
    float weights_buf[OUTPUT_NUM1][INPUT_NUM1];
    float weights_flatten_buf[OUTPUT_NUM1*INPUT_NUM1];

    int err;

    for (int i = 0; i < OUTPUT_NUM1; i++)
    {
        /* code */
        for (int j = 0; j < INPUT_NUM1; j++)
        {
            /* code */
            weights_buf[i][j] = i*INPUT_NUM1 + j;
        }
    }

    for (int i = 0; i < OUTPUT_NUM1; i++)
    {
        /* code */
        output_data_hw[i] = 0;
        output_data_sw[i] = 0;
    }
    
    
    for (int i = 0; i < OUTPUT_NUM1; i++)
    {
        /* code */
        for (int j = 0; j < INPUT_NUM1; j++)
        {
            /* code */
            weights_flatten_buf[i*INPUT_NUM1 + j] = weights_buf[i][j];
        }
    }

    for (int i = 0; i < OUTPUT_NUM1; i++)
    {
        /* code */
        PROCESS:for (int j = 0; j < INPUT_NUM1; j++)
        {
            /* code */
            output_data_sw[i] += input_data_buf[j] * weights_buf[i][j];
        }
        #ifdef active
        output_data_sw[i] = (output_data_buf[i] > 0) ? output_data_buf[i] : 0;
        #endif
    }

    full_connection_layer1(input_data_buf,output_data_hw,weights_flatten_buf,0);

    for (int i = 0; i < OUTPUT_NUM1; i++)
    {
        /* code */
        if(output_data_sw[i] != output_data_hw[i])
            err ++;
    }
    if(err)
        cout << "test have " << err <<"  errors!" << endl;
    else
    {
        cout << "test pass !!" << endl;
    }
    
    
    return err;

}
